import {LegalPage,LegalSection} from "../legal-content";
export const metadata={title:"Terms and Conditions | CreteXchange",description:"Terms governing use of the CreteXchange website and platform."};
export const dynamic="force-static";
export default function Terms(){return <LegalPage eyebrow="Legal" title="Terms and Conditions" intro="These terms govern access to and use of the CreteXchange website, platform, and related services." updated="August 26, 2026">
  <p>These Terms and Conditions (the “Terms”) are an agreement between you and V8 Industries LLC, the operator of CreteXchange (“CreteXchange,” “we,” “us,” or “our”). By accessing or using CreteXchange, you agree to these Terms. If you do not agree, do not use the service.</p>
  <LegalSection title="1. Eligibility and authority"><p>You must be at least 18 years old and legally able to enter a binding agreement. If you use CreteXchange for a company or other organization, you represent that you have authority to bind that organization.</p></LegalSection>
  <LegalSection title="2. What CreteXchange provides"><p>CreteXchange provides digital tools that help drivers, haulers, facilities, contractors, producers, and public-sector participants exchange information about construction-material recovery opportunities and document recovery activity.</p><p>CreteXchange is a technology platform. Unless expressly stated otherwise, we are not a carrier, broker, disposal facility, recycler, contractor, material owner, or operator of participating facilities. We do not take custody of material and do not direct drivers to use a particular route or facility.</p></LegalSection>
  <LegalSection title="3. Independent operational decisions"><p>Drivers remain responsible for deciding whether, when, and how to travel to a facility and for complying with traffic laws, employer policies, site rules, vehicle requirements, and safe-driving practices. Do not interact with a device while driving.</p><p>Facilities independently determine what materials they accept, their operating requirements and availability, and any recovery incentive they choose to offer. Listings, hours, accepted materials, capacity, incentives, and access conditions may change and should be confirmed when necessary.</p></LegalSection>
  <LegalSection title="4. Accounts and accurate information"><p>You must provide accurate, current information; safeguard your credentials; and promptly notify us of suspected unauthorized use. You are responsible for activity performed through your account unless prohibited by law.</p><p>You may not impersonate another person or organization, create deceptive accounts, falsify facility or drop information, manipulate verification records, or use CreteXchange for unlawful activity.</p></LegalSection>
  <LegalSection title="5. Facility responsibilities"><p>Facility users are responsible for maintaining accurate listings, accepted-material information, access instructions, incentive terms, and required permits or authorizations. A facility must not list or accept material it cannot lawfully receive, handle, process, or store.</p></LegalSection>
  <LegalSection title="6. Drop verification"><p>CreteXchange may use account information, timestamps, location signals, geofence results, photographs, facility confirmations, and related records to evaluate whether a drop is verified. Verification indicates that available platform evidence met the applicable workflow; it is not a legal certification of material composition, environmental compliance, title, weight, or regulatory status.</p><p>We may delay, deny, reverse, or review a verification when information is incomplete, inconsistent, duplicated, fraudulent, or reasonably disputed.</p></LegalSection>
  <LegalSection title="7. Fees, incentives, and payments"><p>At the current launch model, drivers and facility owners are not charged a subscription or enrollment fee. Facilities may set a per-drop driver recovery incentive from $0 to any amount they choose. CreteXchange charges the facility $5 for each verified drop processed through the platform.</p><p>Where payment functionality is enabled, additional payment-provider terms may apply. Payment timing, payout eligibility, reversals, failed charges, and dispute procedures may be shown in the platform. Each participant is responsible for its own taxes, reporting, and legal obligations. CreteXchange does not characterize facility-funded incentives as tips or provide tax advice.</p><p>We may change pricing prospectively after providing notice. A pricing change will not retroactively alter a completed transaction.</p></LegalSection>
  <LegalSection title="8. User content and permissions"><p>You retain ownership of information and materials you submit, including photographs, listing information, messages, and verification evidence (“User Content”). You grant CreteXchange a worldwide, non-exclusive, royalty-free license to host, store, reproduce, process, display, and use User Content as reasonably necessary to operate, secure, improve, and document the service and comply with law.</p><p>You represent that you have the rights and permissions needed to submit User Content and that it does not violate law or another party’s rights.</p></LegalSection>
  <LegalSection title="9. Location and camera features"><p>Some features require permission to access location data, a camera, or photographs. You control device permissions, but disabling them may prevent use of facility discovery, geofence, or verification features. Location and map information may be approximate and must not be used as a substitute for safe navigation or site instructions.</p></LegalSection>
  <LegalSection title="10. Prohibited conduct"><p>You may not interfere with the service; bypass security or access controls; introduce malicious code; scrape or copy the service at unreasonable scale; reverse engineer protected portions except where law permits; misuse personal information; submit false recovery events; or use the service to facilitate illegal dumping, improper disposal, unsafe conduct, or regulatory violations.</p></LegalSection>
  <LegalSection title="11. Intellectual property"><p>CreteXchange, its software, branding, designs, documentation, and platform content are owned by V8 Industries LLC or its licensors and are protected by applicable intellectual-property laws. These Terms provide a limited, revocable, non-transferable right to use the service for its intended purpose; they do not transfer ownership.</p></LegalSection>
  <LegalSection title="12. Third-party services"><p>The service may rely on or link to third-party mapping, hosting, payment, communications, storage, or other services. Those services may have separate terms and privacy practices. We are not responsible for third-party services outside our control.</p></LegalSection>
  <LegalSection title="13. Availability and changes"><p>We may modify, suspend, or discontinue features; perform maintenance; establish usage limits; or change eligibility requirements. We do not guarantee uninterrupted access, continuous facility availability, a particular recovery result, incentive, route, environmental outcome, or financial return.</p></LegalSection>
  <LegalSection title="14. Disclaimers"><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, CRETEXCHANGE IS PROVIDED “AS IS” AND “AS AVAILABLE.” WE DISCLAIM IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. INFORMATION PROVIDED THROUGH THE SERVICE MAY BE INCOMPLETE, DELAYED, OR INACCURATE.</p><p>Nothing in the service replaces professional legal, environmental, safety, tax, engineering, transportation, or regulatory advice.</p></LegalSection>
  <LegalSection title="15. Limitation of liability"><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, V8 INDUSTRIES LLC AND ITS AFFILIATES, OFFICERS, AND SERVICE PROVIDERS WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR LOST PROFITS, DATA, USE, GOODWILL, OR BUSINESS INTERRUPTION ARISING FROM THE SERVICE.</p><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR AGGREGATE LIABILITY ARISING OUT OF THE SERVICE OR THESE TERMS WILL NOT EXCEED THE GREATER OF $100 OR THE AMOUNT YOU PAID DIRECTLY TO CRETEXCHANGE DURING THE SIX MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM. Some jurisdictions do not allow certain limitations, so portions of this section may not apply to you.</p></LegalSection>
  <LegalSection title="16. Indemnification"><p>To the extent permitted by law, you agree to defend, indemnify, and hold harmless V8 Industries LLC and its affiliates, officers, and service providers from claims, losses, liabilities, and reasonable costs arising from your unlawful use of the service, your User Content, your facility or transportation operations, or your violation of these Terms or another party’s rights.</p></LegalSection>
  <LegalSection title="17. Suspension and termination"><p>We may suspend or terminate access when reasonably necessary to protect users, investigate fraud or security issues, enforce these Terms, comply with law, or address risk to the service. You may stop using the service at any time and may request account deletion subject to lawful retention requirements.</p></LegalSection>
  <LegalSection title="18. Governing law and disputes"><p>These Terms are governed by the laws of the State of Texas, without regard to conflict-of-law principles. Unless applicable law requires otherwise, disputes that cannot be resolved informally will be brought in a state or federal court with jurisdiction in Collin County, Texas.</p></LegalSection>
  <LegalSection title="19. Changes to these Terms"><p>We may update these Terms. Material changes will be posted with a revised “Last updated” date and, when appropriate, additional notice. Continued use after updated Terms become effective constitutes acceptance to the extent permitted by law.</p></LegalSection>
  <LegalSection title="20. Contact"><p>Questions about these Terms may be sent to <a href="mailto:mstiger@cretexchange.com">mstiger@cretexchange.com</a> or directed to (469) 269-6709.</p></LegalSection>
</LegalPage>}
