import {LegalPage,LegalSection} from "../legal-content";
export const metadata={title:"Privacy Policy | CreteXchange",description:"How CreteXchange collects, uses, shares, and protects information."};
export default function Privacy(){return <LegalPage eyebrow="Privacy" title="Privacy Policy" intro="This policy explains how CreteXchange collects, uses, shares, retains, and protects information." updated="August 26, 2026">
  <p>CreteXchange is operated by V8 Industries LLC (“CreteXchange,” “we,” “us,” or “our”). This Privacy Policy applies to our website, platform, and related services (collectively, the “Service”).</p>
  <LegalSection title="1. Information we collect"><h3>Information you provide</h3><ul><li>Account and contact information, such as name, email address, telephone number, company, and role.</li><li>Facility, jobsite, vehicle, material, and operational information you submit.</li><li>Photographs, messages, support requests, verification evidence, and other content you provide.</li><li>Transaction and incentive information. Payment-card details are generally collected and processed by our payment provider rather than stored in full by CreteXchange.</li></ul><h3>Information collected through use of the Service</h3><ul><li>Device, browser, IP address, log, diagnostic, and usage information.</li><li>Approximate or precise location information when you grant permission, including information used for facility discovery, geofence evaluation, routing context, and drop verification.</li><li>Camera and photo-library information when you grant permission and choose to capture or upload verification evidence.</li><li>Cookies and similar technologies used for authentication, security, preferences, and service performance.</li></ul></LegalSection>
  <LegalSection title="2. How we use information"><p>We use information to:</p><ul><li>Provide, maintain, personalize, and improve the Service.</li><li>Create and secure accounts and authenticate users.</li><li>Display facility opportunities and support informed destination decisions.</li><li>Evaluate and document recovery events, geofence results, photographs, incentives, fees, and disputes.</li><li>Process payments and payouts where payment features are enabled.</li><li>Communicate service, safety, security, support, and administrative messages.</li><li>Detect fraud, abuse, security incidents, and technical problems.</li><li>Analyze performance and develop aggregated or deidentified insights.</li><li>Comply with law and enforce our agreements.</li></ul></LegalSection>
  <LegalSection title="3. How we share information"><p>We may share information:</p><ul><li>With service providers that support hosting, databases, storage, maps, payments, communications, analytics, security, and customer support.</li><li>Between participating drivers, facilities, contractors, and other users when needed to support an opportunity, visit, verification, incentive, dispute, or requested connection.</li><li>With professional advisers, auditors, insurers, or transaction participants in connection with financing, restructuring, merger, acquisition, or sale of assets.</li><li>When required by law or reasonably necessary to protect rights, safety, security, and the integrity of the Service.</li><li>With your direction or consent.</li></ul><p>We do not sell personal information for money, and we do not use personal information for cross-context behavioral advertising. If our practices change, we will update this policy and provide legally required choices.</p></LegalSection>
  <LegalSection title="4. Location information and photographs"><p>Location and photographic evidence can be important to facility discovery and verified-drop workflows. We collect this information only through enabled platform features and applicable device permissions. You may change permissions through your device or browser, but some features may no longer function.</p><p>Location signals can be imprecise. We may retain location, timestamp, geofence, and image evidence when reasonably necessary for verification, safety, fraud prevention, dispute resolution, auditing, or legal compliance.</p></LegalSection>
  <LegalSection title="5. Data retention"><p>We retain personal information for as long as reasonably necessary for the purposes described in this policy, including account administration, transaction and verification records, security, dispute resolution, regulatory obligations, and enforcement. Retention periods vary by data type and legal requirement. We may retain aggregated or deidentified information where it cannot reasonably identify you.</p></LegalSection>
  <LegalSection title="6. Data security"><p>We use reasonable administrative, technical, and organizational safeguards designed to protect information. No internet transmission or storage system is completely secure, and we cannot guarantee absolute security. Protect your credentials and notify us promptly of suspected unauthorized activity.</p></LegalSection>
  <LegalSection title="7. Your choices and privacy rights"><p>You may update certain account information in the Service and may contact us to request access, correction, deletion, or a copy of personal information, or to opt out of nonessential communications. We may need to verify your identity and may retain information when permitted or required by law.</p><p>Residents of Texas, California, and other jurisdictions may have additional rights where the applicable law covers CreteXchange and the relevant processing. These may include rights to confirm processing, access, correct, delete, or obtain a portable copy of data, and to opt out of certain sales, targeted advertising, sharing, or profiling. CreteXchange does not discriminate against users for exercising applicable privacy rights.</p><p>Submit a request to <a href="mailto:mstiger@cretexchange.com">mstiger@cretexchange.com</a> or call (469) 269-6709. If an applicable law provides an appeal right and we deny a request, you may appeal by replying to our decision with “Privacy Appeal” in the subject line.</p></LegalSection>
  <LegalSection title="8. Children’s privacy"><p>The Service is intended for business users age 18 and older and is not directed to children. We do not knowingly collect personal information from children under 13. If you believe a child has provided personal information, contact us so we can investigate and take appropriate action.</p></LegalSection>
  <LegalSection title="9. Third-party services"><p>The Service may link to or integrate with third-party services. Their privacy practices are governed by their own policies, and this policy does not cover information they process independently.</p></LegalSection>
  <LegalSection title="10. Processing and transfers"><p>Information may be processed in the United States and other locations where our service providers operate. Where required, we use appropriate safeguards for cross-border transfers.</p></LegalSection>
  <LegalSection title="11. Changes to this policy"><p>We may update this Privacy Policy as the Service, our practices, or legal requirements change. We will post the revised policy with an updated date and provide additional notice when required.</p></LegalSection>
  <LegalSection title="12. Contact"><p>Questions or privacy requests may be sent to <a href="mailto:mstiger@cretexchange.com">mstiger@cretexchange.com</a> or directed to (469) 269-6709.</p></LegalSection>
</LegalPage>}
